export enum FeynmanStatus {
  NOT_STARTED = 'NOT_STARTED',
  TO_EXPLAIN = 'TO_EXPLAIN',
  EXPLAINED_OK = 'EXPLAINED_OK',
  EXPLAINED_BADLY = 'EXPLAINED_BADLY',
  TO_REVIEW = 'TO_REVIEW',
  REVIEW_OK = 'REVIEW_OK',
  NEEDS_WORK = 'NEEDS_WORK',
  REVIEW_FAILED = 'REVIEW_FAILED',
}
