package com.ddmspringapp.exosaver.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents a Course entity in the application.
 * This class maps to the "course" table in the database.
 * Provides details about a course such as its title and description.
 * Utilizes Lombok annotations for boilerplate code generation.
 */
@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
@Table(name = "course")
public class Course {

    /**
     * Unique identifier for the Course entity.
     * Mapped to the primary key column in the "course" table.
     * Automatically generated by the database using the IDENTITY strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String title;

    private String description;

    private String objectives;

    private String themes;
}
